### ISSUE TITLE
Strange IP

### ISSUE THREAD

**Issue by shtse8** [krisklosterman/node-open-mining-portal#8]
```
2017-09-28 01:46:45 [Pool]	[dash] (Thread 7) Share accepted at diff 512/15512446.38744073 by shtse8.test[::ffff:198.11.220.46]
```
IP is added `::ffff:` at the beginning. Is this correct? I can see this IP is inserted into MPOS.

**Comment by BaalMcKloud** [comment]
::ffff: is a subnet prefix for IPv4 (32 bit) addresses that are placed inside an IPv6 (128 bit) space.

**Comment by shtse8** [comment]
Thanks for explanation.
